# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/proj.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0/design_1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_50M_0/design_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_resetare_0/design_1_axi_gpio_resetare_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_resetare_0 || ORIG_REF_NAME==design_1_axi_gpio_resetare_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_dividend_0/design_1_axi_gpio_dividend_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_dividend_0 || ORIG_REF_NAME==design_1_axi_gpio_dividend_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_resetare_1/design_1_axi_gpio_resetare_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_resetare_1 || ORIG_REF_NAME==design_1_axi_gpio_resetare_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_start_0/design_1_axi_gpio_start_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_start_0 || ORIG_REF_NAME==design_1_axi_gpio_start_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_divisor_0/design_1_axi_gpio_divisor_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_divisor_0 || ORIG_REF_NAME==design_1_axi_gpio_divisor_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_dividend_1/design_1_axi_gpio_dividend_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_dividend_1 || ORIG_REF_NAME==design_1_axi_gpio_dividend_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RestoringDivision_0_2/design_1_RestoringDivision_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_RestoringDivision_0_2 || ORIG_REF_NAME==design_1_RestoringDivision_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/dolca/Desktop/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
